version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      #Aca ponga la IP de su nodo donde esta los servicios
      URL: '192.168.99.105'
      CREW_PORT: '4001'
      DECK_PORT: '4005'
      CREW_ENTRY: 'api/crew'
    ports:
      - '5000:5000'