version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      #Aca ponga la IP de su nodo donde esta los servicios
      CREW_URL: '192.168.99.105'
      CREW_PORT: '4001'
      LUGGAGE_URL: '192.168.99.109'
      LUGGAGE_PORT: '4004'
    ports:
      - '5000:5000'