version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      #Aca ponga la IP de su nodo donde esta los servicios
      CREW_URL: 'dnode0.centralus.cloudapp.azure.com'
      CREW_PORT: '4001'
      CREW_ENTRY: 'api/crew'
      DECK_URL: 'dnode1.centralus.cloudapp.azure.com'
      DECK_PORT: '4005'
      LUGGAGE_URL: 'dnode1.centralus.cloudapp.azure.com'
      LUGGAGE_PORT: '4004'
      PASSENGER_URL: 'dnode0.centralus.cloudapp.azure.com'
      PASSENGER_PORT: '4002'
      CONFISCATED_URL: 'dnode2.centralus.cloudapp.azure.com'
      CONFISCATED_PORT: '4003'
    ports:
      - '5000:5000'
