version: '2'
services:
  proxy:
    build: proxy/.
    container_name: proxy
    depends_on:
      - api-gateway
    ports:
      - "80:80"
  api-gateway:
    build: api_gateway/.
    container_name: api-gateway
    environment:
      CREW_URL: 'dnode0.centralus.cloudapp.azure.com'
      CREW_PORT: '4001'
      CREW_ENTRY: 'api'
      DECK_URL: 'dnode1.centralus.cloudapp.azure.com'
      DECK_PORT: '4005'
      LUGGAGE_URL: 'dnode1.centralus.cloudapp.azure.com'
      LUGGAGE_PORT: '4004'
      PASSENGER_URL: 'dnode0.centralus.cloudapp.azure.com'
      PASSENGER_PORT: '4002'
      CONFISCATED_URL: 'dnode2.centralus.cloudapp.azure.com'
      CONFISCATED_PORT: '4003'
